---
on: pull_request
name: PR Lints
jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          pdrofile: minimal
          toolchain: nightly
          override: true
          components: clippy, rustfmt

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
