---
on:
  push:
    branches: main

name: Nightly Release

env:
  RELEASE_BIN: usbwatch
  RELEASE_ADDS: >-
    LICENSE-APACHE
    LICENSE-MIT
    nightly-CHANGELOG.md
    README.md

jobs:
  nightly-release:
    name: Nightly Release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          pdrofile: minimal
          toolchain: nightly
          override: true

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install --yes gcc libudev-dev

      - name: Compile
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Install CLOG
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: clog-cli

      - name: Generate Changelog
        run: clog -F -o nightly-CHANGELOG.md -i /dev/null

      - name: Make artifacts dir
        run: mkdir -p artifacts/

      - name: Copy all artifacts into dir
        run: cp target/release/${{ env.RELEASE_BIN }} ${{ env.RELEASE_ADDS }} artifacts/

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - name: Create archive for Linux
        run: cd artifacts/ && tar czf ../${{ env.RELEASE_BIN }}-${{ env.SHA }}-linux-x86_64.tar.gz ./*
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}

      - name: Remove previous Nightly Release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          delete_release: true
          tag_name: nightly
          repo: kbknapp/usbwatch-rs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Nightly Release
        uses: softprops/action-gh-release@v1
        with:
          name: usbwatch Nightly (${{ env.SHA }})
          tag_name: nightly
          prerelease: true
          body_path: nightly-CHANGELOG.md
          files: |
            ${{ env.RELEASE_BIN }}-${{ env.SHA }}-linux-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: kbknapp/usbwatch-rs
          SHA: ${{ steps.short-sha.outputs.sha }}
